### PR TITLE
Update express to 4.5

### PR DESCRIPTION
**Pull request by saibotsivad**
Changes in express since 4.0 are breaking the send module.

### CODE REVIEW

**Comment by spolu** [comment]
Hi Can you update express submodules versions as well ?

```
"body-parser": "1.0.x",
"method-override": "1.0.x",
```

**Comment by saibotsivad** [comment]
Like so?

**Comment by spolu** [comment]
Thanks!

**Comment by spolu** [comment]
published v0.2.9-alpha.5 should get to you through auto-update

**Pull request merged**
