### PR TITLE
Check for dev.devtoolsFrontendUrl when inspecting element with devtool.

### PR DESCRIPTION
**Pull request by aychtang**
Not sure what the root cause is yet, but this patches #13.

### CODE REVIEW

**Comment by spolu** [comment]
Thanks, so there are multiple calls made there one without dev.devtoolsFrontendUrl ?

**Comment by aychtang** [comment]
Yes. Investigating at the moment but basically there are events being handled by stack_devtools_handler without the correct url in some cases. There is still a bug remaining when you inspect a tab element twice for example.

Is it possible to get a good stacktrace in the module manager debugging output?

**Comment by spolu** [comment]
You can always throw an error from there?

**Comment by spolu** [comment]
And I'll reopen #13 then

**Comment by spolu** [comment]
published v0.2.9-alpha.5 should get to you through auto-update

**Pull request merged**
