### PR TITLE
Closing tabs with the middle mouse button

### PR DESCRIPTION
**Pull request by luaks**
Tabs can now be closed using the mddle mouse button.
It's nothing big, but its something I am using a lot when browsing, so I thought it might be a good place to start getting familiar with breach.

### CODE REVIEW

**Comment by spolu** [comment]
Great. Can you make sure to have a space before your `{` ?

**Comment by luaks** [comment]
Done

**Comment by spolu** [comment]
awesome

**Comment by luaks** [comment]
Yay, thanks for the quick responses ;-)

**Pull request merged**
