### PR TITLE
Disabled user selection

### LINKED ISSUE #22: Some elements are selectable
Double clicking the back or forward button or focussing the strip and hitting Cmd+A selects some elements and it's a bit ugly. I don't expect browser UI elements to be selectable.

screenshot

The fix is simple : 

``` css
body {
    -webkit-user-select: none;
}
```

### PR DESCRIPTION
**Pull request by floriancargoet**
By default, double clicking or Cmd/Ctrl+A selects element.
This CSS property disables user selection.
Fixes #22.

I've added this property to the `.strip`rule instead of `body`.

### CODE REVIEW

**Comment by julien-c** [comment]
+1. Was about to push the same.

**Comment by spolu** [comment]
Thanks!

**Comment by spolu** [comment]
I'll publish a new version of the module today... you should get it through auto update

**Comment by spolu** [comment]
published v0.2.9-alpha.5 should get to you through auto-update

**Pull request merged**
