### PR TITLE
removed devtools (to be in separate module)

### PR DESCRIPTION
**Pull request by jonathan-reisdorf**
DevTools should be in separate module. I have created a development module for this purpose (https://github.com/jonathan-reisdorf/mod_development). Feel free to comment or discuss, this is my first PR here, please double check :)
This also contains exposed add/remove methods for the context menu, so that other modules can add/remove entries. Side effect: "Close DevTools" is now only shown when the DevTools are actually opened.

### CODE REVIEW

**Comment by spolu** [comment]
Looks great! You should add the `context_menu_builder` infrastructure though to construct your context menu in devtools. No need for new `add` and `remove` function I believe.

**Comment by jonathan-reisdorf** [comment]
Maybe I am missing something, but how would you do that? I mean, there are already events in the strip module that will fire the context menu for example on right click; if I add the infrastructure in mod_development these events would sum up and build two context menus, or it would at least overwrite potential other context menu entries that might get added in strip module. That way we would always have to keep these entries in sync imho, that's why I added add & remove functionality for entries. But maybe I am thinking in the wrong direction?

**Comment by spolu** [comment]
The code is made such that it can handle context menu builders from multiple modules: https://github.com/breach/breach_core/blob/master/lib/core_tabs.js#L189

**Comment by jonathan-reisdorf** [comment]
ok thanks, it's now changed and the inspector is now also working without mod_strip

**Comment by spolu** [comment]
This is great!

**Comment by spolu** [comment]
You should add your module there: https://github.com/breach/breach_core/wiki/List-of-modules

**Comment by jonathan-reisdorf** [comment]
I did, but you can also add it here as a repo instead if you like

**Comment by spolu** [comment]
Gotcha. Didn't see it before. CooL!

**Comment by spolu** [comment]
Installing it right now :)

**Pull request merged**
