### PR TITLE
Add transparency to tab loading bar

### PR DESCRIPTION
**Pull request by jacobsmith**
Add transparency of 0.3 to .strip .tabs .tab .loading so it is easier
to pick out tabs when they do not have focus.

TODO: Possibly move from hardcoded opacity levels to a user-config
file or dialog.

Author: jacobsmith

breach_tabs_loading

### CODE REVIEW

**Comment by spolu** [comment]
Thanks! I probably won't merge this PR. We've been playing a lot with these settings over the past couple of weeks and decided to remove colors on non active tabs...

Though it's really intersting to explore the idea of having a way to set settings for each modules.

The way I envisioned it was to expose an API in breach_core for modules to set their settings API. And then expose that page in the module manager, so that each module can build their own settings fairly transparenelty.

If you'd like to work on that, please do let me know!

**Comment by jacobsmith** [comment]
That sounds good! I'm just getting into Javascript a little bit more
recently (come from a ruby background) but may look into how hook up a
module config function. On a side note, do you have any recommendations for
how to debug the javascript code that Breach is using while in browser?

**Comment by spolu** [comment]
For client side code, you can use the debugger embedded with the dev tools.

For module code, the debugging tools associated with v8/nodeJS should work in theory but might need some hooks here and there to properly function. You can always print out stuff and go to the module manager `out` link for that module!

**Comment by julien-c** [comment]
@spolu I'd be willing to give a shot at the module settings system next week. I've been thinking about it lately in the context of Chrome extensions (every extension re-create its own setting system there)
The way I'd go about it is create an Angular controller in breach_core (maybe prettified by http://roykolak.github.io/chrome-bootstrap/), accessible from an (optional) context menu element in the module itself, that generates a form from a set of options exposed by the module. Everything being backed by `core_store` as you said. What do you think?

**Comment by spolu** [comment]
Yep, I can't decide if the module should expose a JSON as a config for the system to expose that config automatically through a unified interface for all modules or if each module should provide its own page.

The former is probably better indeed!

**Comment by spolu** [comment]
Side note: We don't want to look like chrome too much :)

**Pull request closed without merging**
